---
- name: Install Nginx Web Server on Ubuntu
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx systemd

- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Replace zigurd.cf
  template:
    src=/home/templates_nginx/zigurd.cf.conf
    dest=/etc/nginx/conf.d/zigurd.cf.conf

- name: Replace nginx.ml
  template:
    src=/home/templates_nginx/zigurd.ml.conf
    dest=/etc/nginx/conf.d/zigurd.ml.conf

